#include "app_clock.h"

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "esp_wifi.h"
#include <time.h>
#include "esp_event.h"
#include "nvs_flash.h"
#include "esp_netif.h"
#include "esp_log.h"
#include "esp_check.h"
#include "esp_log.h"

#include "custom.h"
#include "events_init.h"
#include "gui_guider.h"
#include "lv_port.h"

static const char *TAG = "app_clock";

/* LVGL UI instance generated by GUI Guider */
lv_ui guider_ui = {0};

/* Globals consumed by custom.c */
struct WetherData weatherdata = {0};
struct tm timeinfo = {0};
char WIFI_try = 0;

static void set_timezone_if_unset(void)
{
    /* Configure a default timezone if none has been provided yet */
    const char *tz = getenv("TZ");
    if (tz == NULL || strlen(tz) == 0) {
        setenv("TZ", "EST5EDT,M3.2.0/2,M11.1.0", 1);
        tzset();
    }
}

static void apply_weather_defaults(void)
{
    memset(&weatherdata, 0, sizeof(weatherdata));
    /* Seniverse code 0 == Sunny */
    strncpy(weatherdata.city, "Offline", sizeof(weatherdata.city) - 1);
    strncpy(weatherdata.weather, "0", sizeof(weatherdata.weather) - 1);
    strncpy(weatherdata.weather_1, "10", sizeof(weatherdata.weather_1) - 1);
    strncpy(weatherdata.weather_2, "14", sizeof(weatherdata.weather_2) - 1);
    strncpy(weatherdata.high, "--", sizeof(weatherdata.high) - 1);
    strncpy(weatherdata.humi, "--", sizeof(weatherdata.humi) - 1);
}

static void apply_time_defaults(void)
{
    memset(&timeinfo, 0, sizeof(timeinfo));
    /* Use a reasonable placeholder date/time */
    timeinfo.tm_year = 123; /* Years since 1900 -> 2023 */
    timeinfo.tm_mon = 6;    /* July (0-based) */
    timeinfo.tm_mday = 1;
    timeinfo.tm_hour = 12;
    timeinfo.tm_min = 0;
    timeinfo.tm_sec = 0;
    timeinfo.tm_wday = 6;   /* Saturday */
}

/* -------------------------------------------------------------------------- */
/* External hooks required by custom.c                                        */
/* -------------------------------------------------------------------------- */

void get_weather(void)
{
    /* TODO: Replace with ESP-IDF HTTP client fetching real weather data. */
    apply_weather_defaults();
}

void get_time(void)
{
    set_timezone_if_unset();

    time_t now = 0;
    time(&now);
    if (now <= 1) {
        apply_time_defaults();
        return;
    }

    struct tm local_tm = {0};
    if (localtime_r(&now, &local_tm) == NULL) {
        apply_time_defaults();
        return;
    }

    timeinfo = local_tm;
}

/* -------------------------------------------------------------------------- */

esp_err_t app_clock_start(lv_disp_t *disp)
{
    ESP_RETURN_ON_FALSE(disp != NULL, ESP_ERR_INVALID_ARG, TAG, "display handle is null");

    WIFI_try = 0; /* Treat Wi-Fi as available so timers run, even with placeholders */
    apply_weather_defaults();
    apply_time_defaults();

    if (!lvgl_port_lock(0)) {
        ESP_LOGE(TAG, "Failed to lock LVGL");
        return ESP_ERR_TIMEOUT;
    }

    setup_ui(&guider_ui);
    events_init(&guider_ui);
    custom_init(&guider_ui);

    lvgl_port_unlock();

    app_clock_loop();

    ESP_LOGI(TAG, "Elecrow clock UI initialized");
    return ESP_OK;
}

// --------------------------------------------------------------------------
// Wi-Fi event handler: reports connection status and IP address
// --------------------------------------------------------------------------
static void wifi_event_handler(void* arg, esp_event_base_t event_base,
                               int32_t event_id, void* event_data)
{
    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START) {
        esp_wifi_connect();
        ESP_LOGI(TAG, "Wi-Fi start event received, trying to connect...");
    } else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) {
        ESP_LOGW(TAG, "Wi-Fi disconnected, retrying...");
        esp_wifi_connect();
    } else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
        ip_event_got_ip_t* event = (ip_event_got_ip_t*) event_data;
        ESP_LOGI(TAG, "Got IP Address: " IPSTR, IP2STR(&event->ip_info.ip));
    }
}


void app_clock_loop(void)
{
    // Initialize NVS (required for Wi-Fi)
    ESP_ERROR_CHECK(nvs_flash_init());

    // Initialize network stack and event loop
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    esp_netif_create_default_wifi_sta();

    // Configure Wi-Fi
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    // Register the Wi-Fi event handler
    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, &wifi_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &wifi_event_handler, NULL));

    wifi_config_t wifi_config = {
        .sta = {
            .ssid = "koroks",
            .password = "chespeke",
        },
    };

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));  // Station = connect to a router
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_start());

    ESP_LOGI(TAG, "Wi-Fi started, connecting to %s...", wifi_config.sta.ssid);

}
